// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhR7qLNX52GGID9PhWx2nDJmvstcDsJ04',
    appId: '1:258022384649:web:bd8f721edb847f6d5c04d8',
    messagingSenderId: '258022384649',
    projectId: 'healjai-8f495',
    authDomain: 'healjai-8f495.firebaseapp.com',
    storageBucket: 'healjai-8f495.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4ADNFRMdrSch5YSnkQBbEg5YOIdSJ8I',
    appId: '1:258022384649:android:660c025261c175a25c04d8',
    messagingSenderId: '258022384649',
    projectId: 'healjai-8f495',
    storageBucket: 'healjai-8f495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6eQx9Zc0OE-YpGIooNeob8GxAOR20fP8',
    appId: '1:258022384649:ios:358767e9d5178f375c04d8',
    messagingSenderId: '258022384649',
    projectId: 'healjai-8f495',
    storageBucket: 'healjai-8f495.appspot.com',
    iosBundleId: 'com.example.healjai',
  );
}
